# Generated by Django 4.0 on 2024-04-30 16:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'отдел', 'verbose_name_plural': 'отделы'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='director', to='app_employee.employee', verbose_name='руководитель'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(regex='\\+7\\s\\(\\d{3}\\)\\s\\d{3}-\\d{2}-\\d{2}')], verbose_name='телефон'),
        ),
    ]
